name: spotify_clone

description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:

  sdk: '>=3.1.1 <4.0.0'

dependencies:

  flutter:

    sdk: flutter

  cupertino_icons: ^1.0.2

  dio: ^5.3.3

  flutter_riverpod: ^2.4.1

  flutter_dotenv: ^5.1.0

  riverpod_annotation: ^2.1.6

dev_dependencies:

  flutter_test:

    sdk: flutter

  flutter_lints: ^2.0.3

  riverpod_generator: ^2.3.3

  build_runner: ^2.4.6

  custom_lint: ^0.5.3

  riverpod_lint: ^2.1.1

flutter:

  uses-material-design: true

  assets:

    - lib/.env